### PR TITLE
PR 1.1.1

### PR DESCRIPTION
**Pull request by LausiD**
fix subscripe all to subscribe only for used state

### CODE REVIEW

**Comment by Apollon77** [comment]
passt Du auch package/io-package an dann geht ein update für uns dann mega fix?!

**Comment by LausiD** [comment]
Kann ich gerne mal versuchenVon Samsung-Tablet gesendet
-------- Ursprüngliche Nachricht --------Von: Ingo Fischer <notifications@github.com> Datum: 07.11.18  00:02  (GMT+01:00) An: "ioBroker/ioBroker.fhem" <ioBroker.fhem@noreply.github.com> Cc: LausiD <login@dirk-lausberg.de>, Author <author@noreply.github.com> Betreff: Re: [ioBroker/ioBroker.fhem] PR 1.1.1 (#20) passt Du auch package/io-package an dann geht ein update für uns dann mega fix?!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ioBroker/ioBroker.fhem","title":"ioBroker/ioBroker.fhem","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ioBroker/ioBroker.fhem"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Apollon77 in #20: passt Du auch package/io-package an dann geht ein update für uns dann mega fix?!"}],"action":{"name":"View Pull Request","url":"https://github.com/ioBroker/ioBroker.fhem/pull/20#issuecomment-436441388"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ioBroker/ioBroker.fhem/pull/20#issuecomment-436441388",
"url": "https://github.com/ioBroker/ioBroker.fhem/pull/20#issuecomment-436441388",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ioBroker/ioBroker.fhem] PR 1.1.1 (#20)",
"sections": [
{
"text": "",
"activityTitle": "**Ingo Fischer**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Apollon77",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ioBroker/ioBroker.fhem\",\n\"issueId\": 20,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"ioBroker/ioBroker.fhem\",\n\"pullRequestId\": 20\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ioBroker/ioBroker.fhem/pull/20#issuecomment-436441388"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 406066852\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by LausiD** [comment]
Erledigt :-) Falls ich noch was falsch mache oder besser machen kann bitte sagen

**Comment by Apollon77** [comment]
npm published, in latest repo by tomorrow

**Pull request merged**
